name: 'Hello World'
description: 'Greet someone'
inputs:
  custom_streamlit_component_lib_file:
    required: false
    description: ''
    default: ''

outputs:
  output_directory:
    description: ''
    value: ${{ steps.final_step.outputs.output_directory }}

runs:
  using: "composite"
  steps:
    - name: Link develop version of streamlit-component-lib
      if: inputs.custom_streamlit_component_lib_file != ''
      working-directory: ${{ github.action_path }}/../../../
      shell: bash
      env:
        STREAMLIT_COMPONENT_LIB_FILE: ${{ inputs.custom_streamlit_component_lib_file }}
      run: |
        find examples template template-reactless -name frontend -maxdepth 3 | while IFS= read -r line; do
          (
            cd "${line}";
            npm install "${STREAMLIT_COMPONENT_LIB_FILE}"
          )
        done

    - name: Install node dependencies
      working-directory: ${{ github.action_path }}/../../../
      shell: bash
      run: ./dev.py all-npm-install

    - name: Build frontend code
      working-directory: ${{ github.action_path }}/../../../
      shell: bash
      run: ./dev.py all-npm-build

    - name: Build wheel packages
      working-directory: ${{ github.action_path }}/../../../
      shell: bash
      run: |
        find examples template template-reactless -maxdepth 3 -name '__init__.py' |\
        xargs -n 1 sed -i 's/_RELEASE = False/_RELEASE = True/';

        ./dev.py all-python-build-package

    - name: Set outputs
      working-directory: ${{ github.action_path }}/../../../
      shell: bash
      id: final_step
      run: |
        output_dir="$(readlink -e dist)"
        echo "output_directory=${output_dir}" >> $GITHUB_OUTPUT