# Ship a minimal metadata file that can be picked up by Streamlit at runtime.
[project]
name = "{{ cookiecutter.package_name }}"
version = "0.0.1"

[[tool.streamlit.component.components]]
name = "{{ cookiecutter.import_name }}"
asset_dir = "frontend/build"
